### PR TITLE
Migration to null safety using dart migrate tool

### PR DESCRIPTION
**Pull request by miquelbeltran**
As reported in https://github.com/canonical/dbus.dart/issues/119 we would like to have a version of dbus with null safety support.

In this PR I have applied the guide from dart.dev to perform a null safety migration, using the `dart migrate` tool and following its steps.

I also had to do some changes regarding the use of `Future<void>` to be compatible with the latest dart changes.

Going to be sincere: I haven't tested this, also I don't see tests that I can run, so I cannot warranty that this is bug free, this will require someone who has knowledge of how the package works to go through it and check it.

Please feel free to perform any changes directly without asking and take the work from there.

Also, I would need to sign the https://ubuntu.com/legal/contributors/agreement but I need to give a "Canonical Project Manager or contact" which I don't have, so let me know who to mention.

Thanks for taking time on this and hopefully you will consider this change.

### CODE REVIEW

**Comment by robert-ancell** [comment]
Thanks for this @miquelbeltran! You can set me as a contact for the CLA form.

Very happy to see this change, hopefully we can get it to work soon (I haven't done a null safety migration yet).

**Comment by robert-ancell** [comment]
I've landed some small changes to make this migration easier. Looking through the code here there's currently too many return values marked as nullable that shouldn't be (I'm guessing the migration tool sprinkles these where it's not sure). I'll keep trying to break down what you've got and see what we can land.

**Comment by miquelbeltran** [comment]
Thanks @robert-ancell! I submitted the CLA.

A;so yes, I could not decide if a type should be nullable or not so I left it as the migration tool made it.

**Comment by robert-ancell** [comment]
I've done the null safety migration in https://github.com/canonical/dbus.dart/pull/130. It came out quite different to what the migration tool did :)

**Pull request closed without merging**
