### PR TITLE
Add some convenience for working with D-Bus signatures

### PR DESCRIPTION
**Pull request by jpnurmi**

### CODE REVIEW

**Comment by jpnurmi** [comment]
I have to look up D-Bus signatures quite often because they are so easy to forget. And I keep doing silly mistakes when I think I remember them. :smile: I think something like this would help a lot! /cc @Feichtmeier

**Comment by robert-ancell** [comment]
I could never decide if using `DBusUint32.signature` or `DBusSignature.uint32` was the right way to go. But I guess it doesn't hurt to have both.

I have to say I've never really loved the signature system in DBus/GVariant, hopefully this helps!

**Review by robert-ancell — APPROVED** [review]
LGTM

**Comment by jpnurmi** [comment]
One option could be to collect the constants to a separate `DBusSignatures` class, inspired by `Color` + `Colors` and `Icon` + `Icons` in Flutter.

**Comment by Feichtmeier** [comment]
Very nice idea! Thank you!

**Pull request merged**
