### PR TITLE
Const constructors for integer value types

### LINKED ISSUE #332: Const constructors for DBusInts
Using `assert()` in the initialization list would allow checking the ranges without losing const constructors. What do you think?

For example:
```diff
diff --git a/lib/src/dbus_value.dart b/lib/src/dbus_value.dart
index d4ca526..b3ab38b 100644
--- a/lib/src/dbus_value.dart
+++ b/lib/src/dbus_value.dart
@@ -172,12 +172,9 @@ class DBusInt32 extends DBusValue {
   final int value;
 
   /// Creates a new signed 32 bit integer with the given [value].
-  DBusInt32(this.value) {
-    if (value < -2147483648 || value > 2147483647) {
-      throw ArgumentError.value(
-          value, 'value', 'Int32 must be in range [-2147483648, 2147483647]');
-    }
-  }
+  const DBusInt32(this.value)
+      : assert(value >= -2147483648 || value <= 2147483647,
+            'Int32 must be in range [-2147483648, 2147483647]');
 
   @override
   DBusSignature get signature {
@@ -205,12 +202,9 @@ class DBusUint32 extends DBusValue {
   final int value;
 
   /// Creates a new unsigned 32 bit integer with the given [value].
-  DBusUint32(this.value) {
-    if (value.isNegative || value > 4294967295) {
-      throw ArgumentError.value(
-          value, 'value', 'Uint32 must be in range [0, 4294967295]');
-    }
-  }
+  const DBusUint32(this.value)
+      : assert(value >= 0 && value <= 4294967295,
+            'Uint32 must be in range [0, 4294967295]');
 
   @override
   DBusSignature get signature {
```

Before:
```dart
properties: <String, DBusValue>{
  'foo': DBusInt32(1),
  'bar': const DBusDouble(2.0),
  'baz': const DBusString(''),
};
```
After:
```dart
properties: const <String, DBusValue>{
  'foo': DBusInt32(1),
  'bar': DBusDouble(2.0),
  'baz': DBusString(''),
};
```

Technically, this would be a breaking change because there might be code out there that relies on `ArgumentError`...

### PR DESCRIPTION
**Pull request by jpnurmi**
Close: #332

### CODE REVIEW

**Comment by jpnurmi** [comment]
Plain `dart test` does work fine but the `test_cov` package seems to have some issues with assertion errors. Even passing an explicit `--enable-asserts` flag doesn't help.
```
class Ctor {
  Ctor(int value)
      : assert(value >= 0 && value <= 255, 'Foo must be in range [0, 255]');
}

void func(int value) {
  assert(value >= 0 && value <= 255, 'Foo must be in range [0, 255]');
}

void main() {
  test('assert - passes', () {
    expect(() => throw AssertionError('...'), throwsA(isA<AssertionError>()));
  });

  test('ctor - fails', () {
    expect(() => Ctor(-1), throwsA(isA<AssertionError>()));
  });

  test('func - fails', () {
    expect(() => func(-1), throwsA(isA<AssertionError>()));
  });
}
```
```
00:00 +1 -1: ctor - fails [E]

  Expected: throws <Instance of 'AssertionError'>
    Actual: <Closure: () => DBusByte>
     Which: returned DBusByte:<DBusByte(-1)>
  

  package:test_api/src/expect/expect.dart 137:31     fail
  package:test_api/src/expect/expect.dart 107:7      _expect
  package:test_api/src/expect/expect.dart 46:3       expect
  test/dbus_test.dart 199:5                          main.<fn>
  package:test_api/src/backend/declarer.dart 215:19  Declarer.test.<fn>.<fn>
  ===== asynchronous gap ===========================
  package:test_api/src/backend/declarer.dart 213:7   Declarer.test.<fn>
  ===== asynchronous gap ===========================
  package:test_api/src/backend/invoker.dart 257:7    Invoker._waitForOutstandingCallbacks.<fn>
```

**Comment by jpnurmi** [comment]
Perhaps we could drop `test_cov` and run `flutter test --coverage` instead...? As in, just make use of the Flutter tooling in the CI. It doesn't introduce an actual dependency to Flutter.

```diff
diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
index 13c8b1c..d2ad2c4 100644
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -10,20 +10,19 @@ jobs:
   build:
     runs-on: ubuntu-20.04
 
-    container:
-      image: dart:stable
-
     steps:
       - uses: actions/checkout@v2
 
+      - uses: subosito/flutter-action@v1
+
       - name: Print Dart SDK version
-        run: dart --version
+        run: flutter --version
 
       - name: Install dependencies
-        run: dart pub get
+        run: flutter pub get
 
       - name: Run regression tests
-        run: dart run test_cov
+        run: flutter test --coverage
 
       - name: Upload coverage
         uses: codecov/codecov-action@v1
diff --git a/pubspec.yaml b/pubspec.yaml
index 496532d..9994c55 100644
--- a/pubspec.yaml
+++ b/pubspec.yaml
@@ -23,7 +23,6 @@ dependencies:
 dev_dependencies:
   lints: ^1.0.1
   test: ^1.16.8
-  test_cov: ^1.0.1
 
 executables:
   dart-dbus: dart_dbus
```

**Comment by robert-ancell** [comment]
Does `dart run --enable-asserts test_cov` work?

**Comment by jpnurmi** [comment]
The behavior of `dart run test_cov <file>` is the same as `dart run <file>`. `dart test <file>` does something different. I was going to report a bug but the issue tracker disabled: https://github.com/vitusortner/test_cov

```dart
import 'package:test/test.dart';

void main() {
  test('assert', () {
    expect(() {
      assert(false);
    }, throwsA(isA<AssertionError>()));
  });
}
```
### dart test
```
$ dart test test/assert_test.dart 
00:00 +1: All tests passed!
```
### dart run test_cov
```
$ dart run test_cov test/assert_test.dart
Found 2 test files.
Generated test-all script in test/.test_cov.dart.
Observatory listening on http://127.0.0.1:8181/mf2Nqkw9e-c=/
The Dart DevTools debugger and profiler is available at: http://127.0.0.1:8181/mf2Nqkw9e-c=/devtools/#/?uri=ws%3A%2F%2F127.0.0.1%3A8181%2Fmf2Nqkw9e-c%3D%2Fws
00:00 +0: assert

00:00 +0 -1: assert [E]

  Expected: throws <Instance of 'AssertionError'>
    Actual: <Closure: () => Null>
     Which: returned <null>
  

  package:test_api/src/expect/expect.dart 137:31     fail
  package:test_api/src/expect/expect.dart 107:7      _expect
  package:test_api/src/expect/expect.dart 46:3       expect
  test/assert_test.dart 5:5                          main.<fn>
  package:test_api/src/backend/declarer.dart 215:19  Declarer.test.<fn>.<fn>
  ===== asynchronous gap ===========================
  package:test_api/src/backend/declarer.dart 213:7   Declarer.test.<fn>
  ===== asynchronous gap ===========================
  package:test_api/src/backend/invoker.dart 257:7    Invoker._waitForOutstandingCallbacks.<fn>
  

00:00 +0 -1: Some tests failed.



Consider enabling the flag chain-stack-traces to receive more detailed exceptions.
For example, 'dart test --chain-stack-traces'.


Unhandled exception:
Tests failed with exit code 255
#0      runTestsAndCollect (package:test_cov/src/functions.dart:104:24)
<asynchronous suspension>
#1      main (file:///home/jpnurmi/.pub-cache/hosted/pub.dartlang.org/test_cov-1.0.1/bin/test_cov.dart:17:3)
<asynchronous suspension>
```
### dart run
```
$ dart run test/assert_test.dart
00:00 +0: assert

00:00 +0 -1: assert [E]

  Expected: throws <Instance of 'AssertionError'>
    Actual: <Closure: () => Null>
     Which: returned <null>
  

  package:test_api/src/expect/expect.dart 137:31     fail
  package:test_api/src/expect/expect.dart 107:7      _expect
  package:test_api/src/expect/expect.dart 46:3       expect
  test/assert_test.dart 5:5                          main.<fn>
  package:test_api/src/backend/declarer.dart 215:19  Declarer.test.<fn>.<fn>
  ===== asynchronous gap ===========================
  package:test_api/src/backend/declarer.dart 213:7   Declarer.test.<fn>
  ===== asynchronous gap ===========================
  package:test_api/src/backend/invoker.dart 257:7    Invoker._waitForOutstandingCallbacks.<fn>
  

00:00 +0 -1: Some tests failed.



Consider enabling the flag chain-stack-traces to receive more detailed exceptions.
For example, 'dart test --chain-stack-traces'.


Unhandled exception:
Dummy exception to set exit code.
```

**Review by robert-ancell — APPROVED** [review]
LGTM

**Pull request merged**
