### PR TITLE
Removed unnecessary await in example/signals.dart

### PR DESCRIPTION
**Pull request by yash1200**
In this PR, I have removed the unnecessary await which was added while calling subscribeSignal and some reformatting also.

### CODE REVIEW

**Comment by robert-ancell** [comment]
Thanks @yash1200! Can you please sign the [Canonical contributor license agreement](https://ubuntu.com/legal/contributors)? Apologies for that not being documented yet, I have a task to do that and set it up in the CI. You can set me as the "Canonical Project Manager or contact".

**Comment by yash1200** [comment]
It's done. I signed the Canonical CLA.

**Comment by robert-ancell** [comment]
Thanks @yash1200!

**Comment by yash1200** [comment]
Thank you @robert-ancell

**Pull request merged**
