### PR TITLE
Add helper methods to map DBusArray and DBusDict

### PR DESCRIPTION
**Pull request by robert-ancell**

### CODE REVIEW

**Comment by robert-ancell** [comment]
@jpnurmi I've been holding off this change for a while because I wasn't sure of the right names for these methods - does it make sense to you?

**Comment by jpnurmi** [comment]
What's the difference to `toNative()`? Is the advantage to have stricter type checking?

**Comment by robert-ancell** [comment]
> What's the difference to `toNative()`? Is the advantage to have stricter type checking?

Yes, to throw an exception if it's not correct and to make the code able to be more optimized/safe with the concrete types.

I only intended toNative() to be for convenience for things like logging.

**Review by jpnurmi — APPROVED** [review]
Makes sense, and the naming is ok to me :+1:

**Comment by jpnurmi** [comment]
What about `DBusValue.toArray()`, `DBusValue.toDict()` etc. for convenience?

**Comment by robert-ancell** [comment]
> What about `DBusValue.toArray()`, `DBusValue.toDict()` etc. for convenience?

They would just be aliases of `value as DBusArray` and `value as DBusDict` - do you think it would be worth it?

**Comment by jpnurmi** [comment]
To make it really convenient, we could even take it one step further and provide typed conversion to native values:
```dart
class DBusValue {
  // (value as DBusBoolean).value
  bool toBool();

  // (value as DBusByte).value
  // (value as DBusIntNm).value
  int toInt();

  // (value as DBusUIntNm).value.toUnsigned(Nm)
  int toUInt();

  // (value as DBusDouble).value
  double toDouble();

  // (value as DBusFoo).toNative().toString()
  String toString(); // e.g. not "DBusString('foo')" but "foo"

  // ((value as DBusArray).toNative() as Iterable).cast<T>().toList()
  // ((value as DBusStruct).toNative() as Iterable).cast<T>().toList()
  List<T> toList<T>();

  // ((value as DBusDict).toNative() as Map).cast<K,V>()
  Map<K, V> toMap<K, V>();
}
```

**Comment by jpnurmi** [comment]
Such conversion methods could replace the tedious `(value as DBusFoo).value` pattern:

- Add convenient type conversion helper function: https://github.com/jpnurmi/dbus.dart/commit/9124cc614d8b7a1730afe0e040eee4b996e3bc89
- Port DBusClient to use the conversion helpers as an example: https://github.com/jpnurmi/dbus.dart/commit/c1cd0a6d77364beeb0b2cc7705e475192bbc75d8

**Pull request merged**
