### PR TITLE
Add null-safety support

### LINKED ISSUE #119: Null safety support
Hello! :wave:

We use `dbus` on the Linux implementations of the `battery_plus`, `connectivity_plus` and `network_info_plus` Flutter packages, located here: https://github.com/fluttercommunity/plus_plugins, and we are currently migrating them to null safety. 

Unfortunately this is blocking us.

Do you have any plans on migrating the package to null safety?

I am happy to help with the task. I will try to send you a PR with the changes I think are necessary, but I would definitely need your assistance.

### PR DESCRIPTION
**Pull request by robert-ancell**
Thanks to @miquelbeltran for initiating this and providing an initial branch
that was used when making this branch.

Fixes #119

### CODE REVIEW

**Comment by robert-ancell** [comment]
Things to resolve:
- The CI isn't able to use Dart 1.12
- How do we release this? This will make dbus.dart unusable on older versions of Dart. It seems other packages have pre-release versions, perhaps this is what is required here.

**Comment by miquelbeltran** [comment]
Thanks for taking care of this so quickly!

Yes, the recommended way to proceed with a release is to bump the version number and add `-nullsafety.0` to it. So it would be `0.2.0-nullsafey.0`. 

Your users will have to opt-in by picking a version with `-nullsafety` in it. And it will appear on pub.dev with both versions, stable and nullsafety prerealse.

**Comment by jpnurmi** [comment]
Hi Robert, are there any other concerns or issues besides having to use Dart beta? There's an ongoing effort to migrate the Flutter Community Plus Plugins to null safety. There are a few Linux plugins that depend on dbus.dart, so it would be fantastic to have a pre-release with null safety support if possible.

**Comment by robert-ancell** [comment]
I was just clarifying the version numbering and branches this would require, but I've now clarified that on Discord and we're good to go!

**Comment by robert-ancell** [comment]
https://pub.dev/packages/dbus/versions/0.2.0

**Comment by jpnurmi** [comment]
Awesome, thank you!

**Pull request merged**
