### PR TITLE
Update streams to be broadcast by default

### PR DESCRIPTION
**Pull request by Taha-Firoz**
I think this should do, I'm not 100% sure though but it is what I've done in my generated code to get it to start working as I expected it to.

This should complete [#293](https://github.com/canonical/dbus.dart/issues/293)

### CODE REVIEW

**Comment by Taha-Firoz** [comment]
Okay the email I signed the CLA with wasn't visible, I've made it visible now so the cla-check should pass

**Comment by Taha-Firoz** [comment]
@robert-ancell any idea when the changes on the code generator will be available on pub.dev?

**Review by robert-ancell — APPROVED** [review]
I was thinking that we would need to update the DBus stream classes, but this seems a lot simpler. This way the change is not an API change, so should be easier to release. Thanks!

**Comment by robert-ancell** [comment]
> @robert-ancell any idea when the changes on the code generator will be available on pub.dev?

Published as dbus 0.6.4, thanks for your contributions!

**Pull request merged**
