### PR TITLE
fix: replaced ffi getuid by posix package

### LINKED ISSUE #191: Replace FFI getuid
It would be nice to not have the getuid FFI code and instead use some system library to do this.

### PR DESCRIPTION
**Pull request by aadarshadhakalg**
Fixes: #191 

Use posix package to get uid

### CODE REVIEW

**Comment by robert-ancell** [comment]
The posix package wasn't as established at the time but it seems to be now. How does this handle when running on Windows? @jpnurmi any problems doing this you know of?

**Comment by aadarshadhakalg** [comment]
It seems like the posix package doesnot have windows  getsid() implementation, so for windows it still uses existing ffi implementation.

**Comment by jpnurmi** [comment]
There's also "our own" [stdlibc](https://github.com/ubuntu-flutter-community/stdlibc.dart) but it doesn't support Windows either. Anyway, is it worth adding any library dependency for that one function? Using `dart:ffi` directly wouldn't tie `dbus.dart` to the release schedule of another package...

**Comment by aadarshadhakalg** [comment]
If we can add windows implementation to [stdlibc](https://github.com/ubuntu-flutter-community/stdlibc.dart) then using stdlibc would be a nice. If we can't do that  and we must use ffi to support windows, then adding an extra dependency is not good and we can close this issue I guess.

**Comment by robert-ancell** [comment]
I'm going to agree here with @jpnurmi - the cost of the dependency doesn't exceeds any benefit of removing the code. Let's stick with what we have.

**Pull request closed without merging**
